from tkinter import *
window = Tk()
window.title("Smallest number")
window.geometry("500x400+20+100")
def findSmallest():
    L = []
    L.append(eval(number2.get()))
    L.append(eval(number3.get()))
    L.append(eval(number4.get()))
    NumSmall.set(min(L))

win1 = Label(window, text = "Find the least")
win1.grid(row=0, column=1, columnspan=2,sticky=EW)
lbl1 = Label(window,text = "First number:")
lbl1.grid(row=1, column = 0,sticky=W)
number2 = StringVar()
ent2 = Entry(window,bd=3,textvariable=number2)
ent2.grid(row=1, column = 1)
lbl2 = Label(window,text ="Second number:")
lbl2.grid(row=2, column=0)
number3=StringVar()
ent3 = Entry(window,bd=3,textvariable=number3)
ent3.grid(row=2,column=1)
lbl3 = Label(window,text="Third number:")
lbl3.grid(row=3,column =0, sticky=W)
number4 = StringVar()
ent4 = Entry(window,bd=3,textvariable=number4)
ent4.grid(row=3, column=1)
btn1 = Button(window,text = "Enter",command=findSmallest)
btn1.grid(row=4, column = 1)
lbl4 = Label(window,text="The smallest number among the three is:")
lbl4.grid(row=5,column=0,sticky=W)
NumSmall = StringVar()
ent5 = Entry(window,bd=3,state="readonly",textvariable=NumSmall)
ent5.grid(row=5,column=1)

mainloop()